name: build-and-push
run-name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. コードチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Buildx セットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Dockerfileからキャッシュ付きでビルド
      - name: Build Docker image with GHA cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: my-sample-app:test01
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. ECRにpush

